CXX = g++
CXXFLAGS = -std=c++23 -Wall -Iinclude -Wextra -Wpedantic

TARGET = main
SRC = $(shell find src -name "*.cpp")

all:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

run: all
	./$(TARGET)

clean:
	rm -f $(TARGET)